language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install --editable .
script:
  - pytest -s --verbose --cov=locast2dvr --cov-branch --cov-report term-missing tests
  - coverage report --fail-under=95
